# Generated by Django 5.1.5 on 2025-03-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysusers',
            options={'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
    ]
