# Generated by Django 5.1.5 on 2025-03-18 20:03

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysSReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('department', models.CharField(blank=True, max_length=400, null=True)),
                ('position', models.CharField(blank=True, max_length=400, null=True)),
                ('rep_type', models.CharField(choices=[('001', 'Simple'), ('002', 'Old System')], default='001', max_length=3)),
                ('job', models.BooleanField(default=False)),
                ('uploadable', models.BooleanField(default=False)),
                ('module', models.CharField(blank=True, max_length=200, null=True)),
                ('template', models.FileField(blank=True, null=True, upload_to=reports.models.report_template_path)),
            ],
        ),
    ]
