# Generated by Django 5.1.5 on 2025-03-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(blank=True, max_length=200, null=True)),
                ('list_id', models.IntegerField()),
                ('resource', models.CharField(max_length=400)),
                ('row_number', models.IntegerField()),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.syssreports')),
            ],
        ),
    ]
