# Generated by Django 5.1.5 on 2025-03-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sysmodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysmodules',
            name='module_type',
            field=models.CharField(default='01', max_length=200),
        ),
        migrations.CreateModel(
            name='SysRepParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=10)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.syssreports')),
            ],
            options={
                'unique_together': {('rep', 'param_name')},
            },
        ),
    ]
