# Generated by Django 5.1.5 on 2025-03-24 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_sysmodules_module_type_sysrepparams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SysRepOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('A', 'Active'), ('C', 'Canceled'), ('E', 'Error'), ('S', 'Successful')], default='A', max_length=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_begin', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.IntegerField()),
                ('machine', models.CharField(max_length=400)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.syssreports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Order',
                'verbose_name_plural': 'Report Orders',
                'ordering': ['-date_begin'],
                'indexes': [models.Index(fields=['state'], name='reports_sys_state_c74e95_idx')],
            },
        ),
    ]
