# Generated by Django 5.1.5 on 2025-03-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_sysreporders'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysRepParamsHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=250)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Report Parameter History',
                'verbose_name_plural': 'Report Parameters History',
                'ordering': ['-order'],
            },
        ),
        migrations.AlterModelOptions(
            name='sysmodules',
            options={'verbose_name': 'Report Module', 'verbose_name_plural': 'Report Modules'},
        ),
        migrations.AlterModelOptions(
            name='sysrepparams',
            options={'verbose_name': 'Report Parameter'},
        ),
        migrations.AlterModelOptions(
            name='syssreports',
            options={'verbose_name': 'All Report', 'verbose_name_plural': 'All Reports'},
        ),
        migrations.RemoveIndex(
            model_name='sysreporders',
            name='reports_sys_state_c74e95_idx',
        ),
        migrations.AddField(
            model_name='sysrepparamshis',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.sysreporders'),
        ),
        migrations.AlterUniqueTogether(
            name='sysrepparamshis',
            unique_together={('order', 'param_name')},
        ),
    ]
