# Generated by Django 5.1.5 on 2025-03-25 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_sysrepparamshis_alter_sysmodules_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SysReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.syssreports')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Access',
                'verbose_name_plural': 'Report Accesses',
            },
        ),
    ]
