# Generated by Django 5.1.5 on 2025-03-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_sysreportaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sysreportaccess',
            unique_together={('rep_id', 'user_id')},
        ),
        migrations.CreateModel(
            name='SysAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=255)),
                ('rep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.syssreports')),
            ],
        ),
        migrations.CreateModel(
            name='SysAccessGroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group_code', 'user')},
            },
        ),
    ]
